// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZc_6tYWRHSfGD-Lf9POeR-YYKvuoeJ0',
    appId: '1:484790897610:web:5584ca04f623f1a9bb5d33',
    messagingSenderId: '484790897610',
    projectId: 'tradingapp-18a2c',
    authDomain: 'tradingapp-18a2c.firebaseapp.com',
    storageBucket: 'tradingapp-18a2c.firebasestorage.app',
    measurementId: 'G-9WQ18D91EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt6xAilaN_d0rGofUU2rceRMNKMvmbLBw',
    appId: '1:484790897610:android:0802b2b05285385bbb5d33',
    messagingSenderId: '484790897610',
    projectId: 'tradingapp-18a2c',
    storageBucket: 'tradingapp-18a2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeHEGBZ5VTxmldGGtWyky9NXw0Va6eEAw',
    appId: '1:484790897610:ios:bdd8d2482d051a79bb5d33',
    messagingSenderId: '484790897610',
    projectId: 'tradingapp-18a2c',
    storageBucket: 'tradingapp-18a2c.firebasestorage.app',
    iosBundleId: 'com.example.tradinggapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeHEGBZ5VTxmldGGtWyky9NXw0Va6eEAw',
    appId: '1:484790897610:ios:bdd8d2482d051a79bb5d33',
    messagingSenderId: '484790897610',
    projectId: 'tradingapp-18a2c',
    storageBucket: 'tradingapp-18a2c.firebasestorage.app',
    iosBundleId: 'com.example.tradinggapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHZc_6tYWRHSfGD-Lf9POeR-YYKvuoeJ0',
    appId: '1:484790897610:web:3166e3e951d789bbbb5d33',
    messagingSenderId: '484790897610',
    projectId: 'tradingapp-18a2c',
    authDomain: 'tradingapp-18a2c.firebaseapp.com',
    storageBucket: 'tradingapp-18a2c.firebasestorage.app',
    measurementId: 'G-7KK44FZW8B',
  );
}
